---
steps:
  # Build landing (local context - standalone Next.js app)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/verifactu-landing'
      - '-f'
      - 'apps/landing/Dockerfile'
      - 'apps/landing'

  # Build app (monorepo root context - uses pnpm workspace)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/verifactu-app'
      - '-f'
      - 'apps/app/Dockerfile'
      - '.'

  # Build api (local context - standalone Node.js app)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/verifactu-api'
      - '-f'
      - 'apps/api/Dockerfile'
      - 'apps/api'

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/verifactu-landing']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/verifactu-app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/verifactu-api']

  # Deploy landing to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'verifactu-landing'
      - '--image=gcr.io/$PROJECT_ID/verifactu-landing'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--port=8080'

  # Deploy app to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'verifactu-app'
      - '--image=gcr.io/$PROJECT_ID/verifactu-app'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'

  # Deploy api to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'verifactu-api'
      - '--image=gcr.io/$PROJECT_ID/verifactu-api'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'

images:
  - 'gcr.io/$PROJECT_ID/verifactu-landing'
  - 'gcr.io/$PROJECT_ID/verifactu-app'
  - 'gcr.io/$PROJECT_ID/verifactu-api'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
