export const HOLDED_MCP_TOOL_SCOPES: Record<string, string[]> = {
  holded_list_invoices: ['mcp.read', 'holded.invoices.read'],
  holded_get_invoice: ['mcp.read', 'holded.invoices.read'],
  holded_list_documents: ['mcp.read', 'holded.documents.read'],
  holded_get_document: ['mcp.read', 'holded.documents.read'],
  holded_create_document: ['mcp.read', 'holded.documents.write'],
  holded_update_document: ['mcp.read', 'holded.documents.write'],
  holded_delete_document: ['mcp.read', 'holded.documents.write'],
  holded_list_contacts: ['mcp.read', 'holded.contacts.read'],
  holded_get_contact: ['mcp.read', 'holded.contacts.read'],
  holded_create_contact: ['mcp.read', 'holded.contacts.write'],
  holded_update_contact: ['mcp.read', 'holded.contacts.write'],
  holded_delete_contact: ['mcp.read', 'holded.contacts.write'],
  holded_list_treasury_accounts: ['mcp.read', 'holded.treasury.read'],
  holded_get_treasury_account: ['mcp.read', 'holded.treasury.read'],
  holded_create_treasury_account: ['mcp.read', 'holded.treasury.write'],
  holded_update_treasury_account: ['mcp.read', 'holded.treasury.write'],
  holded_list_expense_accounts: ['mcp.read', 'holded.expenses.read'],
  holded_get_expense_account: ['mcp.read', 'holded.expenses.read'],
  holded_create_expense_account: ['mcp.read', 'holded.expenses.write'],
  holded_update_expense_account: ['mcp.read', 'holded.expenses.write'],
  holded_delete_expense_account: ['mcp.read', 'holded.expenses.write'],
  holded_list_numbering_series: ['mcp.read', 'holded.numbering.read'],
  holded_create_numbering_series: ['mcp.read', 'holded.numbering.write'],
  holded_update_numbering_series: ['mcp.read', 'holded.numbering.write'],
  holded_delete_numbering_series: ['mcp.read', 'holded.numbering.write'],
  holded_list_products: ['mcp.read', 'holded.products.read'],
  holded_get_product: ['mcp.read', 'holded.products.read'],
  holded_create_product: ['mcp.read', 'holded.products.write'],
  holded_update_product: ['mcp.read', 'holded.products.write'],
  holded_delete_product: ['mcp.read', 'holded.products.write'],
  holded_list_sales_channels: ['mcp.read', 'holded.saleschannels.read'],
  holded_get_sales_channel: ['mcp.read', 'holded.saleschannels.read'],
  holded_create_sales_channel: ['mcp.read', 'holded.saleschannels.write'],
  holded_update_sales_channel: ['mcp.read', 'holded.saleschannels.write'],
  holded_delete_sales_channel: ['mcp.read', 'holded.saleschannels.write'],
  holded_list_warehouses: ['mcp.read', 'holded.warehouses.read'],
  holded_get_warehouse: ['mcp.read', 'holded.warehouses.read'],
  holded_create_warehouse: ['mcp.read', 'holded.warehouses.write'],
  holded_update_warehouse: ['mcp.read', 'holded.warehouses.write'],
  holded_delete_warehouse: ['mcp.read', 'holded.warehouses.write'],
  holded_list_payments: ['mcp.read', 'holded.payments.read'],
  holded_get_payment: ['mcp.read', 'holded.payments.read'],
  holded_create_payment: ['mcp.read', 'holded.payments.write'],
  holded_update_payment: ['mcp.read', 'holded.payments.write'],
  holded_delete_payment: ['mcp.read', 'holded.payments.write'],
  holded_list_taxes: ['mcp.read', 'holded.taxes.read'],
  holded_list_payment_methods: ['mcp.read', 'holded.paymentmethods.read'],
  holded_list_contact_groups: ['mcp.read', 'holded.contactgroups.read'],
  holded_get_contact_group: ['mcp.read', 'holded.contactgroups.read'],
  holded_create_contact_group: ['mcp.read', 'holded.contactgroups.write'],
  holded_update_contact_group: ['mcp.read', 'holded.contactgroups.write'],
  holded_delete_contact_group: ['mcp.read', 'holded.contactgroups.write'],
  holded_list_remittances: ['mcp.read', 'holded.remittances.read'],
  holded_get_remittance: ['mcp.read', 'holded.remittances.read'],
  holded_list_services: ['mcp.read', 'holded.services.read'],
  holded_get_service: ['mcp.read', 'holded.services.read'],
  holded_create_service: ['mcp.read', 'holded.services.write'],
  holded_update_service: ['mcp.read', 'holded.services.write'],
  holded_delete_service: ['mcp.read', 'holded.services.write'],
  holded_list_accounts: ['mcp.read', 'holded.accounts.read'],
  holded_list_bookings: ['mcp.read', 'holded.crm.read'],
  holded_list_projects: ['mcp.read', 'holded.projects.read'],
  holded_get_project: ['mcp.read', 'holded.projects.read'],
  holded_list_project_tasks: ['mcp.read', 'holded.projects.read'],
  holded_create_invoice_draft: ['mcp.read', 'holded.invoices.write'],
};

export const HOLDED_MCP_SUPPORTED_SCOPES = [
  'mcp.read',
  'holded.invoices.read',
  'holded.invoices.write',
  'holded.documents.read',
  'holded.documents.write',
  'holded.contacts.read',
  'holded.contacts.write',
  'holded.accounts.read',
  'holded.crm.read',
  'holded.projects.read',
  'holded.treasury.read',
  'holded.treasury.write',
  'holded.expenses.read',
  'holded.expenses.write',
  'holded.numbering.read',
  'holded.numbering.write',
  'holded.products.read',
  'holded.products.write',
  'holded.saleschannels.read',
  'holded.saleschannels.write',
  'holded.warehouses.read',
  'holded.warehouses.write',
  'holded.payments.read',
  'holded.payments.write',
  'holded.taxes.read',
  'holded.paymentmethods.read',
  'holded.contactgroups.read',
  'holded.contactgroups.write',
  'holded.remittances.read',
  'holded.services.read',
  'holded.services.write',
] as const;

export type HoldedMcpScopePreset = 'full' | 'readonly';

const READONLY_SCOPE_SET = HOLDED_MCP_SUPPORTED_SCOPES.filter((scope) => !scope.endsWith('.write'));

export function getHoldedMcpScopePreset(preset: HoldedMcpScopePreset) {
  return preset === 'readonly' ? READONLY_SCOPE_SET : HOLDED_MCP_SUPPORTED_SCOPES;
}

export function buildScopeString(scopes: readonly string[]) {
  return Array.from(new Set(scopes)).join(' ');
}
