// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDahYslX6rDZSWcHk4sCXOZnU9cmqgEt0o',
    appId: '1:536174799167:web:cecdc93b701e133869cb8a',
    messagingSenderId: '536174799167',
    projectId: 'verifactu-business',
    authDomain: 'verifactu-business.firebaseapp.com',
    storageBucket: 'verifactu-business.firebasestorage.app',
    measurementId: 'G-69BBK7850J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqm3YFq9Z35FMCbYguRTenGnniHe7lyrE',
    appId: '1:536174799167:android:24c5a26ae575bec269cb8a',
    messagingSenderId: '536174799167',
    projectId: 'verifactu-business',
    storageBucket: 'verifactu-business.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzRLvAQosVAIZZ7AxRZI4_ay3jg8MTkpg',
    appId: '1:536174799167:ios:2fff495a9bc4781569cb8a',
    messagingSenderId: '536174799167',
    projectId: 'verifactu-business',
    storageBucket: 'verifactu-business.firebasestorage.app',
    iosClientId: '536174799167-jqg3vg78gt1r5275tv92uogfkcrcu64j.apps.googleusercontent.com',
    iosBundleId: 'business.verifactu.verifactuMobile',
  );
}
