#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-dry-run}" # dry-run | apply

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI no está instalado" >&2
  exit 1
fi

if [[ "$MODE" != "dry-run" && "$MODE" != "apply" ]]; then
  echo "Uso: $0 [dry-run|apply]" >&2
  exit 1
fi

edit_issue() {
  local number="$1"
  local title="$2"
  local body="$3"

  if [[ "$MODE" == "dry-run" ]]; then
    echo "would update #$number -> $title"
    return 0
  fi

  gh issue edit "$number" --title "$title" --body "$body" >/dev/null
  echo "updated #$number"
}

edit_issue 51 "[FEATURE] S0-01 Eliminar menciones a marcas y dejar copy genérico" $'## Description\nEliminar cualquier mención a marcas (p.ej. Holded) en web pública y app. Sustituir por copy genérico: “Integración con tu programa de contabilidad vía API”.\n\n## Problem It Solves\nEvita dependencia de proveedor y alinea el posicionamiento: integración genérica vía API solo en Empresa/PRO; export AEAT en todos.\n\n## Proposed Solution\n- [ ] Búsqueda global en repo: Holded, holded, logos/ids/rutas/textos\n- [ ] Reemplazar copy por:\n  - [ ] “Integración con tu programa de contabilidad vía API”\n  - [ ] “Conecta tu programa contable mediante API Key”\n- [ ] Revisar: landing, /planes, /integraciones, app Integraciones, tooltips, emails/plantillas, docs\n\n### Acceptance Criteria\n- [ ] Búsqueda global “Holded/holded” devuelve 0 resultados en strings visibles\n\n## Alternative Solutions\nMantener marcas ocultas internamente -> descartado (riesgo de leaks de copy/UI).\n\n## Mockups or Examples\nN/A\n\n## Additional Context\nSprint 0. Bloquea S0-02.'

edit_issue 52 "[FEATURE] S0-02 Actualizar matriz de planes y feature flags (AEAT Excel todos; API Empresa/PRO)" $'## Description\nActualizar permisos por plan y copy: export AEAT Excel en todos los planes; integración contable vía API solo en Empresa y PRO.\n\n## Problem It Solves\nClarifica oferta y evita gating incorrecto. Alinea backend + UI + marketing.\n\n## Proposed Solution\n- [ ] Flags por plan:\n  - [ ] canExportAeatBooks = true (BÁSICO/PYME/Empresa/PRO)\n  - [ ] canUseAccountingApiIntegration = true (Empresa/PRO)\n  - [ ] canBidirectionalQuotes = true (Empresa/PRO)\n- [ ] Web pública:\n  - [ ] Tabla de planes: “Libros oficiales (Excel) compatibles AEAT” en todos\n  - [ ] Empresa/PRO: “Integración con tu programa de contabilidad vía API”\n- [ ] App:\n  - [ ] Impuestos/export visible para todos\n  - [ ] Integraciones/API: upsell o disabled en BÁSICO/PYME; funcional en Empresa/PRO\n\n### Acceptance Criteria\n- [ ] Tenant BÁSICO puede exportar AEAT Excel\n- [ ] Tenant BÁSICO NO puede guardar API key\n- [ ] Tenant Empresa/PRO SÍ puede guardar API key\n\n## Alternative Solutions\nGating por roles/usuarios -> no sustituye gating por plan.\n\n## Mockups or Examples\nTabla de planes (landing).\n\n## Additional Context\nBlocked by #51.'

edit_issue 53 "[FEATURE] S1-01 Prisma: TenantProfile (perfil fiscal mínimo)" $'## Description\nAñadir perfil fiscal mínimo por tenant (sin limitar tipos de empresa).\n\n## Problem It Solves\nPermite aceptar cualquier empresa y generar exports coherentes (NIF/VAT, razón social, dirección).\n\n## Proposed Solution\n- [ ] Añadir modelo TenantProfile:\n  - [ ] tenantId unique\n  - [ ] country default "ES"\n  - [ ] taxId, legalName, tradeName?\n  - [ ] fiscalAddress JSON\n  - [ ] taxRegime? (solo sugerencias)\n- [ ] Migración + backfill razonable\n\n### Acceptance Criteria\n- [ ] Tenant puede guardar/editar perfil fiscal sin “autónomo/SL” hardcoded\n\n## Alternative Solutions\nGuardar en settings JSON -> peor validación y consultas.\n\n## Mockups or Examples\nPantalla de perfil/ajustes (si existe).\n\n## Additional Context\nSprint 1.'

edit_issue 54 "[FEATURE] S1-02 Prisma: TenantIntegration genérica + SyncLog" $'## Description\nCrear base de integración contable genérica (provider=accounting_api) y logs.\n\n## Problem It Solves\nBase estable para conectar API key y luego implementar sync sin rehacer datos.\n\n## Proposed Solution\n- [ ] TenantIntegration: provider, apiKeyEnc, status, lastSyncAt, lastError\n- [ ] SyncLog: level, message, data JSON\n- [ ] Cifrado apiKeyEnc (env var/wrapper existente)\n\n### Acceptance Criteria\n- [ ] Empresa/PRO guarda API key cifrada y ve estado connected/error\n\n## Alternative Solutions\nGuardar API key en claro -> no aceptable.\n\n## Mockups or Examples\nPantalla Integraciones.\n\n## Additional Context\nRequerido por S1-07 y Sprint 2.'

edit_issue 55 "[FEATURE] S1-03 Prisma: Extender Expense para clasificación fiscal/export" $'## Description\nAñadir campos a Expense para export AEAT robusto, incluyendo “no factura”.\n\n## Problem It Solves\nEvita exports incompletos y permite tratamiento correcto de deducibilidad/no-factura.\n\n## Proposed Solution\n- [ ] Expense.docType: invoice/ticket/receipt/bank_fee/payroll/other\n- [ ] Expense.taxCategory: iva_deducible/iva_no_deducible/suplido/exento/...\n- [ ] Expense.aeatConcept?, Expense.aeatKey?\n\n### Acceptance Criteria\n- [ ] Gastos confirmados guardan docType/taxCategory y se reflejan en export\n\n## Alternative Solutions\nCampos en JSON -> menos robusto.\n\n## Mockups or Examples\nUI de confirmación de gasto.\n\n## Additional Context\nBloquea exports.'

edit_issue 56 "[FEATURE] S1-04 Backend: Export Libros AEAT (Excel) ventas/recibidas (todos los planes)" $'## Description\nEndpoints para descargar libros oficiales (Excel) compatibles AEAT: ventas y recibidas.\n\n## Problem It Solves\nFuncionalidad core incluida en todos los planes.\n\n## Proposed Solution\n- [ ] Endpoints:\n  - [ ] GET /api/aeat/books/sales?from&to&format=xlsx\n  - [ ] GET /api/aeat/books/purchases?from&to&format=xlsx\n- [ ] XLSX con columnas estables + warnings por fila si faltan datos\n- [ ] Tests: IVA 21/10/4, exento, no deducible, suplidos, no-factura\n\n### Acceptance Criteria\n- [ ] Cualquier plan puede descargar XLSX sin errores fatales\n- [ ] Filas incompletas se exportan con warnings\n\n## Alternative Solutions\nSolo CSV -> menos usable para usuarios.\n\n## Mockups or Examples\nN/A\n\n## Additional Context\nDepends on #55.'

edit_issue 57 "[FEATURE] S1-05 Backend: Export 303/130 + Preview (Excel)" $'## Description\nEndpoints de export de impuestos (303/130) y preview (totales) para UI.\n\n## Problem It Solves\nPermite al usuario validar cifras antes de exportar e importar en su flujo.\n\n## Proposed Solution\n- [ ] Endpoints:\n  - [ ] GET /api/aeat/export/303?period&format=xlsx\n  - [ ] GET /api/aeat/export/130?period&format=xlsx\n  - [ ] GET /api/aeat/preview/303?period\n  - [ ] GET /api/aeat/preview/130?period\n- [ ] Preview: totales por tipo IVA y resumen ingresos/gastos\n\n### Acceptance Criteria\n- [ ] Preview coincide con export (mismos totales)\n\n## Alternative Solutions\nSin preview -> peor UX/soporte.\n\n## Mockups or Examples\nPantalla impuestos.\n\n## Additional Context\nDepends on #56.'

edit_issue 58 "[FEATURE] S1-06 App: Pantalla Impuestos (export AEAT Excel para todos)" $'## Description\nUI para seleccionar periodo, ver preview y descargar Excel.\n\n## Problem It Solves\nHace usable el export para todos los planes sin soporte manual.\n\n## Proposed Solution\n- [ ] Menú Impuestos (303/130)\n- [ ] Selector de periodo + botón “Exportar Excel”\n- [ ] Mostrar preview (totales) antes del export\n\n### Acceptance Criteria\n- [ ] Usuario BÁSICO puede exportar desde UI (sin gating)\n\n## Alternative Solutions\nAcceso solo desde backend/admin -> no.\n\n## Mockups or Examples\nImpuestos -> IVA (303), IRPF (130).\n\n## Additional Context\nDepends on #57.'

edit_issue 59 "[FEATURE] S1-07 App: Integración “Programa contable vía API” (solo Empresa/PRO)" $'## Description\nPantalla para conectar API key (guardar y mostrar estado). Sin marcas.\n\n## Problem It Solves\nActiva el upsell y prepara Sprint 2 (sync).\n\n## Proposed Solution\n- [ ] Integraciones -> Programa contable (API)\n- [ ] Empresa/PRO: input API key + guardar (cifrado) + status + lastError\n- [ ] BÁSICO/PYME: upsell/disabled\n\n### Acceptance Criteria\n- [ ] Solo Empresa/PRO puede guardar API key\n- [ ] No hay menciones de marcas\n\n## Alternative Solutions\nOcultar el menú -> reduce conversión.\n\n## Mockups or Examples\nPantalla Integraciones.\n\n## Additional Context\nDepends on #54 y #52.'

edit_issue 60 "[FEATURE] S2-01 Prisma: IntegrationMap + SyncOutbox" $'## Description\nAñadir mapeo local↔remoto e outbox con retries.\n\n## Problem It Solves\nPermite sync fiable e idempotente (no duplicar en el programa contable).\n\n## Proposed Solution\n- [ ] IntegrationMap: entityType, localId, remoteId, hash, lastPushedAt\n- [ ] SyncOutbox: status, attempts, nextRunAt + índices\n\n### Acceptance Criteria\n- [ ] Migración aplicada y accesible\n\n## Alternative Solutions\nSync “directo” sin outbox -> frágil.\n\n## Mockups or Examples\nN/A\n\n## Additional Context\nDepends on #54.'

edit_issue 61 "[FEATURE] S2-02 Backend: Worker Outbox + retries + idempotencia (Empresa/PRO)" $'## Description\nProcesar outbox: pending→done/error, reintentos, logs y hash idempotente.\n\n## Problem It Solves\nEvita duplicados, soporta caídas temporales de la API y da trazabilidad.\n\n## Proposed Solution\n- [ ] Worker (cron/queue)\n- [ ] Backoff retries\n- [ ] Hash idempotencia por payload canónico\n- [ ] SyncLog por ejecución\n- [ ] Gating por plan (solo Empresa/PRO)\n\n### Acceptance Criteria\n- [ ] No duplica; errores reintentan; logs visibles\n\n## Alternative Solutions\nRetries manuales -> soporte costoso.\n\n## Mockups or Examples\nN/A\n\n## Additional Context\nDepends on #60.'

edit_issue 62 "[FEATURE] S2-03 Backend: Encolar outbox en contactos/productos/facturas/gastos (Empresa/PRO)" $'## Description\nEmitir eventos outbox al crear/actualizar entidades canónicas.\n\n## Problem It Solves\nAutomatiza la sincronización con el programa contable en Empresa/PRO.\n\n## Proposed Solution\n- [ ] Encolar “upsert” para:\n  - [ ] contacts (clientes/proveedores)\n  - [ ] products\n  - [ ] invoices (ventas)\n  - [ ] expenses (gastos)\n- [ ] Payload canónico estable\n\n### Acceptance Criteria\n- [ ] Empresa/PRO crea factura -> outbox pending\n- [ ] BÁSICO/PYME no encola nada\n\n## Alternative Solutions\nSync solo manual -> peor UX.\n\n## Mockups or Examples\nN/A\n\n## Additional Context\nDepends on #61 y #52.'

edit_issue 63 "[FEATURE] S2-04 App: Estado de sincronización (Empresa/PRO)" $'## Description\nUI para ver logs, estados y reintentar eventos.\n\n## Problem It Solves\nReduce soporte y hace el sync “operable” por el usuario/admin.\n\n## Proposed Solution\n- [ ] Página estado: últimos SyncLog + filtros\n- [ ] Badges por entidad: synced/pending/error\n- [ ] Acción “Reintentar”\n\n### Acceptance Criteria\n- [ ] Usuario Empresa/PRO ve errores y reintenta desde UI\n\n## Alternative Solutions\nSolo admin -> menos autonomía.\n\n## Mockups or Examples\nIntegraciones -> Estado de sincronización.\n\n## Additional Context\nDepends on #61.'

edit_issue 64 "[FEATURE] S3-01 Prisma: Quote + SyncConflict" $'## Description\nAñadir entidad Quote y conflictos para bidireccional.\n\n## Problem It Solves\nPermite presupuestos sincronizados en ambos sentidos sin pérdida de datos.\n\n## Proposed Solution\n- [ ] Quote (draft/sent/accepted/rejected/expired, lines, totals, source)\n- [ ] SyncConflict (both_modified, localData/remoteData, resolve)\n- [ ] IntegrationMap entityType += quote\n\n### Acceptance Criteria\n- [ ] CRUD quotes posible sin integrar aún\n\n## Alternative Solutions\nEvitar bidireccional -> no cumple requerimiento.\n\n## Mockups or Examples\nVentas -> Presupuestos.\n\n## Additional Context\nDepends on #60.'

edit_issue 65 "[FEATURE] S3-02 Backend: CRUD Quotes + convert-to-invoice" $'## Description\nEndpoints de presupuestos y conversión a factura.\n\n## Problem It Solves\nCierra el flujo comercial (presupuesto -> factura) y prepara sync.\n\n## Proposed Solution\n- [ ] Endpoints quotes + acciones send/accept/reject\n- [ ] convert-to-invoice crea invoice local + outbox (Empresa/PRO)\n\n### Acceptance Criteria\n- [ ] Quote aceptado -> factura creada correctamente\n\n## Alternative Solutions\nConversión manual -> errores.\n\n## Mockups or Examples\nBotón “Convertir a factura” en detalle.\n\n## Additional Context\nDepends on #64.'

edit_issue 66 "[FEATURE] S3-03 Backend: Sync bidireccional Quotes + conflictos (Empresa/PRO)" $'## Description\nPull/push de presupuestos y conflictos de edición concurrente.\n\n## Problem It Solves\nEvita “pisados” y permite operar con programa contable externo.\n\n## Proposed Solution\n- [ ] Pull quotes remoto + upsert local\n- [ ] Push quotes local vía outbox\n- [ ] Si ambos cambiaron -> SyncConflict open\n- [ ] Endpoints:\n  - [ ] listar conflictos\n  - [ ] resolver (usar local / usar remoto)\n\n### Acceptance Criteria\n- [ ] Conflictos no pisan datos y requieren resolución\n\n## Alternative Solutions\n“Last write wins” -> peligroso.\n\n## Mockups or Examples\nN/A\n\n## Additional Context\nDepends on #65 y #61.'

edit_issue 67 "[FEATURE] S3-04 App: Presupuestos + UI Conflictos (Empresa/PRO)" $'## Description\nUI de presupuestos + resolución de conflictos.\n\n## Problem It Solves\nHace operable el bidireccional sin intervención técnica.\n\n## Proposed Solution\n- [ ] Ventas -> Presupuestos (list + detail)\n- [ ] Acciones + convertir a factura\n- [ ] UI Conflictos: comparar versión “Sistema” vs “Programa contable”\n\n### Acceptance Criteria\n- [ ] Usuario Empresa/PRO resuelve conflictos desde UI\n\n## Alternative Solutions\nResolver solo por admin -> soporte.\n\n## Mockups or Examples\nPantalla conflictos.\n\n## Additional Context\nDepends on #66.'

echo "Done ($MODE)."
