FROM node:20-slim AS base
RUN corepack enable
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
COPY . .
RUN pnpm install --filter verifactu-landing
RUN pnpm run build --filter=verifactu-landing

FROM node:20-slim AS runner
WORKDIR /app
COPY --from=base /app/apps/landing/.next/standalone ./.next/standalone
COPY --from=base /app/apps/landing/.next/static ./.next/static
COPY --from=base /app/apps/landing/public ./public
ENV NODE_ENV=production
EXPOSE 3000
CMD ["ls", "-lR"]
